apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      meta.helm.sh/release-name: famousapp
      meta.helm.sh/release-namespace: mbtacz-multicontainer-helm
    creationTimestamp: "2022-10-03T06:21:39Z"
    generation: 1
    labels:
      app.kubernetes.io/instance: famousapp
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: famouschart
      app.kubernetes.io/version: 1.16.0
      helm.sh/chart: famouschart-0.1.0
    name: famousapp-famouschart
    namespace: mbtacz-multicontainer-helm
    resourceVersion: "160548192"
    selfLink: /apis/apps/v1/namespaces/mbtacz-multicontainer-helm/deployments/famousapp-famouschart
    uid: f527d116-aec2-4fc0-98ad-20447fe29e19
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app.kubernetes.io/instance: famousapp
        app.kubernetes.io/name: famouschart
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/instance: famousapp
          app.kubernetes.io/name: famouschart
      spec:
        containers:
        - env:
          - name: QUOTES_HOSTNAME
            value: famousapp-mariadb
          - name: QUOTES_DATABASE
            value: quotesdb
          - name: QUOTES_USER
            value: quotes
          - name: QUOTES_PASSWORD
            value: quotespwd
          image: quay.io/redhattraining/famous-quotes:2.1
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: famouschart
          ports:
          - containerPort: 8000
            name: http
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        serviceAccount: famousapp-famouschart
        serviceAccountName: famousapp-famouschart
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2022-10-03T06:23:04Z"
      lastUpdateTime: "2022-10-03T06:23:04Z"
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: "2022-10-03T06:21:39Z"
      lastUpdateTime: "2022-10-03T06:23:04Z"
      message: ReplicaSet "famousapp-famouschart-c79c686bd" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
